#!/usr/bin/env ruby
require 'yaml'

#production:
#  project_name:
#    method: imap
#    host: mail.domain.exp
#    password: secret123
#    username: loginname
#  project2_name:
#    method: imap
#    host: mx.domain.exp
#    password: secret321
#    username: loginname
#
#development:
#  project_name:
#    method: pop
#    host: pop3.demo.exp
#    password: h1dden
#    login: username

config=YAML.load_file('/etc/redmine/default/mail2ticket.yml')

config.each do |enviroment,projects|
  projects.each do |project,options|
    command = "bundle exec rake  --silent  redmine:email:receive_" + options["method"] + " RAILS_ENV=\"" + enviroment +  "\" host="+ options["host"] + " username=" + options["username"] + " password=" + options["password"] + "  move_on_success=read move_on_failure=failed project=" + project  + "  allow_override=project"
    Dir.chdir("/usr/share/redmine/") do
      exec(command)
    end
  end
end


#TODO: RAKE WAY
#require 'rake'
#rake = Rake.application
#rake.init
# you can import addition *.rake files
# app.add_import '/usr/share/redmine/Rakefile'
#rake.load_rakefile
#rake['db:test:prepare'].invoke()

