#!/usr/bin/env ruby
require 'yaml'

cfgFile = '/etc/redmine/default/mail2ticket.yml';

if File.exist?(cfgFile)
  config=YAML.load_file(cfgFile)
  config.each do |enviroment,projects|
    projects.each do |project,options|
      command = "bundle exec rake  --silent  redmine:email:receive_" + options["method"] + " RAILS_ENV=\"" + enviroment +  "\" host="+ options["host"] + " username=" + options["username"] + " password=" + options["password"] + "  move_on_success=read move_on_failure=failed project=" + project  + "  allow_override=project"
      Dir.chdir("/usr/share/redmine/") do
        exec(command)
      end
    end
  end

  #TODO: RAKE WAY
  #require 'rake'
  #rake = Rake.application
  #rake.init
  # you can import addition *.rake files
  # app.add_import '/usr/share/redmine/Rakefile'
  #rake.load_rakefile
  #rake['db:test:prepare'].invoke()

else
  puts " Config file " + cfgFile + " not exists"
end
  
