#!/bin/sh
# postinst script for redmine-mail2ticket

set -e

CFG="/etc/redmine/default/mail2ticket.yml"

if [ ! -f $CFG ] ; then

    . /usr/share/debconf/confmodule

    db_get redmine-mail2ticket/enviroment
    db_get redmine-mail2ticket/project
    db_get redmine-mail2ticket/method
    db_get redmine-mail2ticket/host
    db_get redmine-mail2ticket/password
    db_get redmine-mail2ticket/username

    echo > $CFG 
    echo "$enviroment:" >> $CFG 
    echo "  $project:" >> $CFG 
    echo "    method: $method" >> $CFG 
    echo "    host: $host" >> $CFG 
    echo "    password: $password" >> $CFG 
    echo "    username: $username" >> $CFG 

    if [ "$1" = "configure" ]; then
        db_version 2.0
        if [ -f /etc/init.d/cron ] ; then
            if [ -x /usr/sbin/invoke-rc.d ]; then
                invoke-rc.d cron reload 3>/dev/null || true
            else
                /etc/init.d/cron reload 3>/dev/null || true
            fi
        fi
    fi
fi

#DEBHELPER#

exit 0
